version: 0.2

phases:
  pre_build:
   commands:
     - echo Logging in to Amazon ECR...
     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637994078207.dkr.ecr.ap-south-1.amazonaws.com
  #     - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dockerdemorepo .
      - docker tag dockerdemorepo:latest 637994078207.dkr.ecr.ap-south-1.amazonaws.com/dockerdemorepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 637994078207.dkr.ecr.ap-south-1.amazonaws.com/dockerdemorepo:latest